extends: standard
env:
  node: true
plugins:
  - standard
  - promise
  - node
rules:
  no-console: 2
  require-jsdoc: 0
  valid-jsdoc: 0
  space-before-function-paren:
    - "error"
    -
      anonymous: "always"
      named: "never"
      asyncArrow: "always"
  node/no-deprecated-api: 2
  node/no-missing-import: 2
  node/no-missing-require: 2
